Upload:
  Bucket:
    default:
      AccessKeyId: xxxx
      AccessKeySecret: xxxx
      Endpoint: oss-accelerate.aliyuncs.com
      UrlEndpoint: xxx.oss-accelerate.aliyuncs.com
      Bucket: xxxx
      PathPrefix: image
    pdf:
      AccessKeyId: xxxxx
      AccessKeySecret: xxxxx
      Endpoint: oss-accelerate.aliyuncs.com
      UrlEndpoint: xxxx.oss-accelerate.aliyuncs.com
      Bucket: xxxx
      PathPrefix: pdf
Hexo:
  KeyWord:
    - "敏感词"
    - "敏感词2"
  Ignore:
    - hexo-home